#!/bin/bash

BUILDDIR=${1:-build_asl}

#
# XCODE
#
BUILDDIR=${BUILDDIR} USE_SYSTEM_BOOST=ON TOOLSET=xcode   BUILDMODE=RELEASE sh cmake_build.sh
BUILDDIR=${BUILDDIR} USE_SYSTEM_BOOST=ON TOOLSET=xcode   BUILDMODE=DEBUG   sh cmake_build.sh
