#!/bin/bash
set -e

BUILDDIR=${1:-../build_asl}

#
# CLANG
#
BUILDDIR=${BUILDDIR} USE_STD_THREAD_LOCAL=ON  USE_SYSTEM_BOOST=OFF TOOLSET=clang++ BUILDMODE=RELEASE sh cmake_build.sh
BUILDDIR=${BUILDDIR} USE_STD_THREAD_LOCAL=ON  USE_SYSTEM_BOOST=OFF TOOLSET=clang++ BUILDMODE=DEBUG   sh cmake_build.sh

# clang does not link with a GCC6 boost (ABI tag)
# don't know how to test this so disabling on Linux for now
if [ $(uname) != "Linux" ]; then
BUILDDIR=${BUILDDIR} USE_STD_THREAD_LOCAL=ON  USE_SYSTEM_BOOST=ON  TOOLSET=clang++ BUILDMODE=RELEASE sh cmake_build.sh
BUILDDIR=${BUILDDIR} USE_STD_THREAD_LOCAL=ON  USE_SYSTEM_BOOST=ON  TOOLSET=clang++ BUILDMODE=DEBUG   sh cmake_build.sh
fi

#
# GCC
#
BUILDDIR=${BUILDDIR} USE_STD_THREAD_LOCAL=ON  USE_SYSTEM_BOOST=OFF TOOLSET=g++     BUILDMODE=RELEASE sh cmake_build.sh
BUILDDIR=${BUILDDIR} USE_STD_THREAD_LOCAL=ON  USE_SYSTEM_BOOST=OFF TOOLSET=g++     BUILDMODE=DEBUG   sh cmake_build.sh
BUILDDIR=${BUILDDIR} USE_STD_THREAD_LOCAL=ON  USE_SYSTEM_BOOST=ON  TOOLSET=g++     BUILDMODE=RELEASE sh cmake_build.sh
BUILDDIR=${BUILDDIR} USE_STD_THREAD_LOCAL=ON  USE_SYSTEM_BOOST=ON  TOOLSET=g++     BUILDMODE=DEBUG   sh cmake_build.sh

