name: Doxygen

on:
  release:
    types: [published]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install dependencies
        uses: ssciwr/doxygen-install@v2

      - name: Configure CMake with docs
        run: cmake --preset docs

      - name: Build documentation
        run: cmake --build --preset docs --target docs

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./build/docs/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
